server:
  port: 8080

spring:
  datasource:
    username: your username
    password: you password
    url: jdbc:mysql://localhost:3306/search_engine

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
# example values

indexing-settings:
  sites:
#    - url: https://discord.com
#      name: Лента.ру
    - url: http://www.playback.ru
      name: Nightman
    - url: https://skillbox.ru
      name: Skillbox




